name: service_extensions
version: 0.1.0
description: >-
  A package to add type safety and a discovery service to VM service extensions.

repository: https://github.com/devoncarew/service_extensions

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.31.0
